### ISSUE TITLE
Bump base rocker/geospatial image to version 4.3.0 sometimes between Nov 6 – 10

### ISSUE THREAD

**Issue by GeorgianaElena** [2i2c-org/utoronto-r-image#9]
### Context

To fix https://github.com/2i2c-org/infrastructure/issues/3178. That issue has more context.

**Comment by GeorgianaElena** [comment]
Ping @damianavila and @2i2c-org/engineering! Nathan from UToronto would like to explicitly setup a day and time when we will make this change to inform the community .

Also, they said it's ok to also push this work until the start of Jan when other (?) work is scheduled to happen.

In case I'm out of support when this happens, note that when we setup this details we need to update them in https://2i2c.freshdesk.com/a/tickets/1082

**Comment by yuvipanda** [comment]
My suggestion is that we do this during this window, so we don't overload the January window - that is when we're planning on removing R from jupyter.utoronto.ca completely. I'll wait for @damianavila to do support prioritization though.

**Comment by damianavila** [comment]
I agree with @yuvipanda and this is why yesterday I added this one to the sprint iteration starting today.
I was planning to assign someone but I noticed @yuvipanda is already working on it so syncing the assignee to reflect reality.

**Comment by yuvipanda** [comment]
This is done.
